### ISSUE TITLE
Feature: User can claim egg. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

When the user is in range, they can claim the egg and view the egg contents. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will see a "Claim Egg!" button when they're in range, at which time they'll click and see the egg contents (image and message). 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-30 at 9 19 05 AM](https://user-images.githubusercontent.com/88848572/147774174-6f903c5f-7b1c-4ee7-8e48-93cf4a178a75.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Add the image and message to egg details component, and conditionally render the image and message if the user clicks "Claim Egg!"

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
