### ISSUE TITLE
Bug: Map getting stuck on default location

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#14]
#### Desired Behavior

> ##### The app should ...

Load immediately and the viewport should center on the user's location with the rendered eggs. 

#### Actual Behavior

> ##### The app does this instead ...

Half the time, the app gets stuck trying to find the user's location. 

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Hit refresh a few times, it seems to be random. 

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Check network requests when loading
- [ ] Check for state updates while loading (especially useEffect hooks)
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
