### ISSUE TITLE
Feature: User can navigate to their profile page via navbar

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to click the profile icon on the navbar and view their profile, which will contain their username, profile picture, and collected eggs. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the profile icon on the navbar, they'll see their own profile page with all their collected and dropped eggs. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-30 at 5 12 16 PM](https://user-images.githubusercontent.com/88848572/147797767-fa4c632b-e56d-45ce-9d64-4fb5fe6b3307.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to process requests for user information, user-created eggs, and user-collected eggs. 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a navbar component to toggle between the map and the user's profile page. 
- [ ] Create a profile component to hold collected data about user and user's eggs. 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
