### ISSUE TITLE
Feature: User can view an events feed of egg-claims, egg-drops, and new users. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to view a feed that displays events like egg-claims and egg-drops, ie "Matt just dropped an egg!" or "Matt just claimed an egg"!

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the 'feed' icon, they will see a list of 'events' or 'actions' taken by other users. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-01 at 12 27 03 PM](https://user-images.githubusercontent.com/88848572/147859570-ebb2ea74-c6d9-4384-acad-83d1199b9acc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Add additional sql insert statements to existing requests to update events table
- [ ] Configure 'server/index.js' to accept fetch requests from the client and return events table
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a fetch request for the events table
- [ ] Create a component to display events
- [ ] Configure navbar to route user to events component
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
