### ISSUE TITLE
Feature: User can upload profile image

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to upload their own profile image. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the edit icon, they'll be able to click an 'upload profile image' button to add their own image. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-03 at 8 24 19 AM](https://user-images.githubusercontent.com/88848572/147954675-151bd0ee-9752-4a66-840a-e3ca112eef09.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to accept post requests for profile image and insert them into the proper table. 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update profile page component to allow users to upload a profile photo.

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
