### ISSUE TITLE
Bug: User submitted images must be private and only visible to that user

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#21]
#### Desired Behavior

> ##### The app should ...

Only users who've claimed a particular egg should ever be able to view that egg's contents. 

#### Actual Behavior

> ##### The app does this instead ...

The images are not completely private, and others could find and view them via url. 

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Create middleware to check user's credentials before allowing them to view eggs, images, and messages. 
- [ ] Update index.js to filter requests for images. 
- [ ] Test with HTTPie

- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
