### ISSUE TITLE
Bug: User images should be compressed. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#23]
#### Desired Behavior

> ##### The app should ...

Compress user submitted images, which would be essential for scaling the app. 

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Install image compressor client-side. 
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
