### ISSUE TITLE
Feature: User can send follow requests to other users. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#25]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to search for another user and send a "follow" request to another user. The recipient will receive the notification in their notifications page. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user navigates to the search page, they will see a search input that will live filter users. Once the desired user is found, they can then click "follow" to send a follow request. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-03 at 4 49 31 PM](https://user-images.githubusercontent.com/88848572/147995720-2baf08e2-840b-4871-a671-1d112c3591e1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to include a 'notifications' table. 

### ☁️ Server

- [ ] Update `server/index.js` to insert a 'notification' when the user requests to follow.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a notifications page. 
- [ ] Add a 'notification' post request to communicate to the backend. 
- [ ] Include options for the follow request "Accept" / "Ignore".

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
