### ISSUE TITLE
Feature: User can live search for another user. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#26]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to search for another user. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user navigates to the search page, they can search for a user and see the results filtered live. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-01-04 at 11 57 28 AM](https://user-images.githubusercontent.com/88848572/148116394-7076ef31-e052-4229-aba3-428a0dacee86.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to accept get requests for usernames. 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a search page to display users. 
- [ ] Update component to live filter by user input. 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
