### ISSUE TITLE
Feature: User can view notifications

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#29]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to view notifications from other users, such as follow requests and when another user claims their egg. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user opens the home page (map) they will see a red bell if they have notifications. Upon clicking the notifications icon, they'll navigate to the notifications page wherein they can view their notifications. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-05 at 8 49 37 AM](https://user-images.githubusercontent.com/88848572/148256599-90930906-107f-4bb8-addd-ab2af4508a72.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to accept GET requests for users notifications
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to display notifications
- [ ] Update map and profile to display the notifications icon if the user has notifications

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
