### ISSUE TITLE
Feature: User can accept or reject follow requests

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#31]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose whether to accept or reject a follow request. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user checks their notifications, they will have the option to accept or reject a follow request. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-01-05 at 10 55 38 AM](https://user-images.githubusercontent.com/88848572/148273041-f5516a07-b0bb-4baa-ac44-d8a58537116f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to update the followers table and set isFollowing to 'TRUE'.
- [ ] Update `server/index.js` to delete egg notifications and any follow requests that have been accepted or rejected when the user navigates away from the notifications page.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update profile component to include follower count. 
- [ ] Add button to notifications page to accept/reject/follow back. 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
