### ISSUE TITLE
Feature: User can view followers and following in the user profile

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#33]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can see their followers and following by clicking on 'followers' and 'following' in their profile. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user navigates to their profile page, they can click 'followers' or 'following' and view those usernames and profile photos. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-05 at 3 53 55 PM](https://user-images.githubusercontent.com/88848572/148306393-2249c5af-e277-4ab5-8500-974bfb3f3eb9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Update profile component with click handlers to conditionally render eggs, followers, and following.

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
