### ISSUE TITLE
Bug: User must refresh to see notifications

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#35]
#### Desired Behavior

> ##### The app should ...

The user should see notifications upon signing in and not have to refresh. I believe this is a bug with the json webtoken authorization. 

#### Actual Behavior

> ##### The app does this instead ...

The app does not display notifications until the user refreshes the page or navigates back to the map. 

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Sign in and refresh the page from the map. 

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Test the authorization middleware and check for the token at sign in. 
- [ ] Move the authorization middleware higher in the app. 
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
