### ISSUE TITLE
Feature: User can drop an egg exclusively claimable by followers

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#36]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

When the user creates an egg, they can choose whether or not they want it claimable by everyone or only followers. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon creating an egg, the user will see two options for "Who can claim this egg?" They can choose between "anyone" and "followers" so that the egg is only claimable by those who follow them. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-06 at 10 02 56 AM](https://user-images.githubusercontent.com/88848572/148429698-d038c463-df3d-4e68-b0fb-db9f022b04ac.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to include a "canClaim" column in the "egg" table which will default to "anyone". 

### ☁️ Server

- [ ] Update `server/index.js` to store eggs with the new "canClaim" value. 
- [ ] Update `server/index.js` to query all public eggs and follower eggs for the current user. 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update createEgg component to include radio options for who can claim the egg. 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
