### ISSUE TITLE
Feature: User can drop a "private" egg, only claimable by one specific user. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#38]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can send an egg that's only claimable by one, user-specified follower. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user creates an egg, they will have the option to click "private" and choose from a list of their followers. When they've chosen a follower and submitted the egg, that user will be notified of the private egg. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-06 at 4 35 25 PM](https://user-images.githubusercontent.com/88848572/148472483-37be34ce-1e12-489a-b42e-a58da8393832.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to include a 'privateUserId' column in the 'egg' table.

### ☁️ Server

- [ ] Update `server/index.js` to add a notification to the recipient of the private egg. 
- [ ] Update `server/index.js` to return private eggs to specified users when the map loads. 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update the createEgg component to include a radio option for 'private' and a select element for all of the users' followers. 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
