### ISSUE TITLE
Feature: User can click on the egg photo in their profile to view the image in full size. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#40]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to view a full-size image of their chosen egg. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on an egg in their profile, they'll be redirected to an "egg Display" component that will display the image in full size along with details like "created on", "from", and "claimed on"

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-07 at 8 40 11 AM](https://user-images.githubusercontent.com/88848572/148576627-c6f9a253-1cdd-43ca-a393-cafd011019e1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Create a component to display egg details and full size image from the profile page. 
- [ ] Create click handlers to open the egg display when egg images are clicked in the profile. 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
