### ISSUE TITLE
Feature: User can delete eggs from profile. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#43]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to delete an egg from their profile. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on an egg in their profile, they'll be redirected to the eggDisplay component and see the egg details. Below the image and details, they'll see a "delete egg" option. When they click "delete egg", they'll be asked to confirm that they want to delete the egg, after which they can choose "yes" and the egg will be deleted from their profile. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="895" alt="Screen Shot 2022-01-09 at 10 37 33 AM" src="https://user-images.githubusercontent.com/88848572/148695822-20c0d4e7-3e24-4542-ad45-8c7f7d03f83b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to accept delete requests for the user-specified egg. 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update the eggView component with a delete button and add a click handler to process the delete request upon delete-confirmation. 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
