### ISSUE TITLE
Feature: User can create an egg-marker on the map. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to add an egg to the map that contains a message and photo. The egg will save at that location. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user double-clicks, a modal will request they add a message and image to their 'egg'. When they click "drop egg", an egg will appear at their desired location. 

## 🖼️ Wireframes

![Screen Shot 2021-12-27 at 3 45 47 PM](https://user-images.githubusercontent.com/88848572/147514080-d40e691e-1eda-4f15-ad0f-b4935f602ce8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add the map
- [x] Create a modal for adding an egg
- [x] Create double-click feature with modal
- [x] Make sure the data is being sent to database

### ☁️ Server

- [x] Update `server/index.js` to accept post requests to database for eggs. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to submit egg data (message, image). 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
