### ISSUE TITLE
Feature: User can see how far they are from an egg

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user should be able to click an egg and view its distance, creator, and whether or not it's claimable. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the egg, they should see a description of its distance from their current position. 

## 🖼️ Wireframes

![Screen Shot 2021-12-27 at 5 28 46 PM](https://user-images.githubusercontent.com/88848572/147517913-4fc610e0-a25b-41ca-bd61-899002ba0216.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Modal created for egg details
- [ ] Distance calculated for egg
- [ ] Modal displays whether or not it's claimable. 

### ⚡ Client

- [ ] Create a component to display egg details when eggs are clicked. 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
