### ISSUE TITLE
Feature: User can see all eggs

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDropFinal#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to see all eggs on the map when logged in. 

## 📐 Functionality

When the user logs in, the map will render with all other eggs. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="166" alt="Screen Shot 2021-12-28 at 8 25 14 PM" src="https://user-images.githubusercontent.com/88848572/147627351-cf93ee8a-b70a-4f27-96aa-e863a728c319.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Fetch eggs from database and render to map

### ☁️ Server

- [x] Update `server/index.js` to accept GET requests for eggs
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
